### ISSUE TITLE
Docs: Which countries can this be used in?

### ISSUE THREAD

**Issue by dideler** [Twilio-org/rapid-response-kit#22]
It's unclear to me if this project can be set up to service any area or if it is limited by areas covered by Twilio (or some other service it integrates with).

For example, are docs such as these relevant?
- https://support.twilio.com/hc/en-us/articles/223183068-Twilio-international-phone-number-availability-and-their-capabilities
- https://support.twilio.com/hc/en-us/articles/223181068-Sending-SMS-messages-to-countries-where-Twilio-numbers-aren-t-available

I'm in a situation where I'm quickly evaluating tools to help islands in the Caribbean affected by hurricanes Irma and Jose, mainly Sint Maarten, and it's unclear from a scan of the docs if this is a tool that I can use in that area.

**Comment by kwhinnery** [comment]
Sorry for leaving this issue open for so long - Twilio numbers can reach just about anyone around the world, the only question is whether or not Twilio has local numbers for a market you are interested in reaching (as opposed to having to use international numbers to communicate in that market). 

Sint Maarten has a 721 area code using the +1 country code, and searching the Twilio console indicates we don't have local area code numbers there. However, most +1 markets can receive SMS messages from US mainland numbers without significant fees.
